sudo: required

services:
  - docker

language: python

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - sudo service postgresql stop
  - docker-compose up postgresql
  - cd src
  - pip install -r requirements.txt
  - alembic upgrade head

script:
  - cd src && pytest

