sudo: required

services:
  - postgresql

language: python
python:
    - "3.6"

before_install:
  - psql -U postgres -c "CREATE USER ciex PASSWORD 'ciex'"
  - psql -U postgres -c "CREATE DATABASE ciex_db OWNER ciex"
  - cd src
  - pip3 install -r requirements.txt
  - export PYTHONPATH=${PWD}
  - alembic upgrade head

script:
  - cd src && pytest
