sudo: required

services:
  - postgresql

language: python

before_install:
  - psql -U postgres -c "CREATE USER ciex PASSWORD 'ciex'"
  - psql -U postgres -c "CREATE DATABASE ciex_db OWNER ciex"
  - cd src
  - pip install -r requirements.txt
  - alembic upgrade head

script:
  - cd src && pytest
